In [3]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [4]:
import tkinter

In [5]:
unimport tkinter

SyntaxError: invalid syntax (<ipython-input-5-9cec810d8584>, line 1)

In [6]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [7]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [8]:
conda list

SyntaxError: invalid syntax (<ipython-input-8-277aa8f17352>, line 1)

In [9]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.zero((2,3))

AttributeError: module 'numpy' has no attribute 'zero'

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [17]:
np.one((3,4))

AttributeError: module 'numpy' has no attribute 'one'

In [18]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [20]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
np.random.rand(5)

array([ 0.5698517 ,  0.43835041,  0.31682693,  0.41138   ,  0.83911528])

In [23]:
np.random.rand(5,5)

array([[ 0.86580799,  0.46530099,  0.7024647 ,  0.09882099,  0.80655369],
       [ 0.4107794 ,  0.4929714 ,  0.4681368 ,  0.62754008,  0.45659192],
       [ 0.8667038 ,  0.42466383,  0.77543813,  0.53939766,  0.62229015],
       [ 0.032023  ,  0.26935992,  0.74855761,  0.51477972,  0.54640572],
       [ 0.77048585,  0.59393741,  0.2648673 ,  0.72733056,  0.03944291]])

In [24]:
np.random.randn(2)

array([-1.21345965,  0.90847813])

In [25]:
np.random.randn(4,4)

array([[-0.24151018, -1.39026845,  0.58124898, -0.03053333],
       [ 1.38423677, -0.21288511, -0.84603256,  1.36862561],
       [ 0.93258747,  0.06188865, -1.90346811,  1.05767233],
       [-0.25394208, -1.78144609,  0.69888499,  0.73888308]])

In [26]:
np.random.randint(1,100)

26

In [28]:
np.random.randint(1,100,100)

array([42, 24, 73, 36, 16, 70, 55,  9,  9,  2, 56, 65, 43, 53, 91, 76, 81,
       94, 42, 30, 68, 90, 80, 45, 97, 82, 22, 77, 48, 83, 84, 61, 27, 77,
       67, 40, 34, 28, 82, 44, 98, 23, 51, 41, 30, 82, 15,  7, 37, 45, 61,
       15, 48, 63, 12, 96, 81, 33,  9, 97, 14, 81, 10, 44,  2, 11, 53, 52,
       79, 51, 25, 35, 34, 15, 10, 91, 98, 48, 74, 40, 79, 68, 59,  6, 29,
       85, 63, 79, 30, 90, 55, 52, 69, 10, 99, 93, 53, 64,  6, 96])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.ranint(0,50,10)

AttributeError: module 'numpy.random' has no attribute 'ranint'

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([39, 46,  0, 16, 29, 45, 16, 34, 33, 18])

In [34]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr

array([39, 46,  0, 16, 29, 45, 16, 34, 33, 18])

In [36]:
ranarr.max()

46

In [37]:
ranarr.min()

0

In [38]:
ranarr

array([39, 46,  0, 16, 29, 45, 16, 34, 33, 18])

In [39]:
ranarr.argmax()

1

In [40]:
ranarr.argmin()

2

In [41]:
ranarr.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [42]:
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')

In [47]:
from numpy.random import randint

In [48]:
randint(2,10)

5